# Site wide configuration

title: Ben Watrous's Website
locale: en_US
logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Ben Watrous
  avatar: bio-photo.jpg
  bio: "Benjamin Watrous is a business development innovator and marketing strategist.  He has established business for global corporations, regional distribution companies, and as an entrepreneur. His strategies and tactics led market research and customer contribution for Novartis’s aquaculture business, a unit of Novartis Consumer Health, which develops, manufactures, and markets biotechnology solutions.  Ben also expanded distribution for an all-natural animal supply company in the Southeastern U.S., solving customers’ direct distribution concerns while increasing revenue over 100%.  Ben’s drive for business development founded an aquatic animal care company, winning long-term business with the largest companies in Las Vegas, including MGM/Mirage Resorts and Station Casinos.  Before entrepreneurism, Ben was an aquarium biologist supporting conservation initiatives at the Shark Reef, the largest public aquarium in Nevada, and remains committed to values in line with environmental and social responsibility.

Benjamin earned Bachelor's degrees in Biology and Psychology from the University of Nevada.  As a graduate student, he also led an in-depth consumer research study of North Carolina’s shellfish consumption at NC State University’s business school.  His broad education and entrepreneurial experience in small to multinational corporations enables him to develop marketing strategies and implement business plans that achieve financial goals.  Benjamin’s current aim involves the application of innovative marketing channels to improve the commercialization of sustainable food products.  
"
  email: benwatrous@yahoo.com
  # Do not include the @ symbol in your Twitter username
  twitter: #username
  linkedin: benwatrous
  github: blwatrou
  orcid: # ID Number (ex. 0000-0000-0000-0000)
  researchgate: #username
  mendeley: #username
  google:
    plus: #username
    analytics:
    verify:
    scholar: #id
  facebook: #username
  instagram: #username
  bing-verify:
  stackoverflow: #123456/username from a "http://stackoverflow.com/users/123456/username" link
  xing: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  disqus-shortname:

# The following adjust the accents for your site. If you would like to further edit colors, fonts, font sizes, etc.
# you may do so in _sass/variables.scss
highlight-color: '#CC0000'
lowlight-color: '#000'

  # NOTE: If you would like your site to be licensed under a creative commons license, uncomment the 'yes' next to the type of license you wish to use.
creative-commons:
  cc-by: #yes
  cc-by-nc: #yes

#DO NOT EDIT BEYOND THIS POINT
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
